---
- name: Add MongoDB GPG Key
  become: yes
  shell: |
    rm /usr/share/keyrings/mongodb-server-{{ mongodb_version }}.gpg && \
    curl -fsSL https://pgp.mongodb.com/server-{{ mongodb_version }}.asc | \
    sudo gpg -o /usr/share/keyrings/mongodb-server-{{ mongodb_version }}.gpg \
    --dearmor
  tags: mongo


- name: Add MongoDB repository (for Ubuntu)
  apt_repository:
    repo: deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-{{ mongodb_version }}.gpg ] https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/{{ mongodb_version }} multiverse
    state: present
  when: ansible_os_family == 'Debian'
  tags: mongo

- name: Add MongoDB repository (for Red Hat)
  yum_repository:
    name: mongodb-org-{{ mongodb_version }}
    description: MongoDB Repository
    baseurl: https://repo.mongodb.org/yum/redhat/{{ ansible_distribution_major_version }}/mongodb-org/{{ mongodb_version }}/x86_64/
    gpgcheck: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc
  when: ansible_os_family == 'RedHat'
  tags: mongo

- name: Install MongoDB packages
  package:
    name: mongodb-org
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'
  tags: mongo

- name: Start and enable MongoDB service
  service:
    name: mongod
    state: started
    enabled: yes
  tags: mongo
